# Generated by Django 3.1.7 on 2021-07-14 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_by', models.CharField(default='Foggy Notions', max_length=100)),
                ('in_association_with', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.CharField(default='Artist', max_length=200)),
                ('artist_one', models.CharField(blank=True, max_length=200, null=True)),
                ('venue', models.CharField(default='Venue', max_length=100)),
                ('date_one', models.DateField()),
                ('date_two', models.DateField(blank=True, null=True)),
                ('date_three', models.DateField(blank=True, null=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('rescheduled_to', models.DateField(blank=True, null=True)),
                ('rescheduled_to_1', models.DateField(blank=True, null=True)),
                ('rescheduled_to_2', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('tickets', models.URLField(blank=True, max_length=1024, null=True)),
                ('tickets_1', models.URLField(blank=True, max_length=1024, null=True)),
                ('tickets_2', models.URLField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('artist_website', models.URLField(blank=True, max_length=1024, null=True)),
                ('artist_website_one', models.URLField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_one'],
            },
        ),
    ]
