# Generated by Django 3.1.7 on 2021-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist_website',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
