# Generated by Django 3.1.7 on 2021-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_concert_artist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist_one',
            field=models.CharField(default='Artist', max_length=200),
        ),
        migrations.AddField(
            model_name='concert',
            name='artist_website_one',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
