# Generated by Django 3.1.7 on 2021-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_auto_20210302_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='artist_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
