# Generated by Django 3.1.7 on 2021-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_auto_20210302_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='tickets_1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='tickets_2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
