# Generated by Django 3.1.7 on 2021-04-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210417_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_info_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
