# Generated by Django 3.1.7 on 2021-04-12 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_by', models.CharField(default='Foggy Notions', max_length=100)),
                ('in_association_with', models.CharField(blank=True, max_length=200, null=True)),
                ('festival_name', models.CharField(default='Festival Name', max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
                ('festival_website', models.URLField(blank=True, max_length=1024, null=True)),
                ('festival_youtube', models.URLField(blank=True, max_length=1024, null=True)),
                ('festival_facebook', models.URLField(blank=True, max_length=1024, null=True)),
                ('festival_instagram', models.URLField(blank=True, max_length=1024, null=True)),
                ('festival_twitter', models.URLField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
    ]
